SAF_001: "Selected Algorithm [{0}] is not SET as SECURE in defined configuration"
SAF_002: "Either the Key/IV/Associated Data used for encryption was different than provided for decryption"
SAF_003: "Provided Key With Length [{0}] bytes is not compatible with selected algorithm [{1}], it should be exact [{2}] bytes long"
SAF_004: "Selected Algorithm [{0}] is either incorrect OR not supported"
SAF_005: "Associated Data can only be SET for algorithm AES_GCM"
SAF_006: "Unable to load desired key with alias [{0}] from the keystore"
SAF_007: "TAG is required while using algorithm AES_GCM for decryption"
SAF_008: "TAG is not required while using algorithm [{0}] for decryption"
SAF_009: "Provided Plaintext is should be Padded or must be at-least 16 bytes or its multiple (16,32,48,...)"
SAF_010: "Either the Mode/Key/IV/Padding used for encryption was different than provided for decryption"
SAF_011: "Usage of Algorithm [{0}] is insecure in client-server architecture"
SAF_012: "Padding in Selected Algorithm [{0}] is incorrect"
SAF_013: "Provided Ciphertext is should be Padded or must be at-least 16 bytes or its multiple (16,32,48,...)"
SAF_014: "Provided IV With Length [{0}] bytes is not compatible with selected algorithm [{1}], it should be of [{2}] bytes"
SAF_015: "Unsecure Key! Key is initialized with all zeros"
SAF_016: "Unable to find Interoperability Configuration for the selected language [{0}]"
SAF_017: "Unable to find Constraints Mapping for the selected algorithm [{0}] in the configuration"
SAF_018: "Key shouldn't be BLANK OR NULL"
SAF_019: "Plaintext shouldn't be BLANK OR NULL"
SAF_020: "Symmetric Algorithm shouldn't be NULL"
SAF_021: "Key Derivation Algorithm shouldn't be NULL"
SAF_022: "Initialization Vector [IV] shouldn't be BLANK OR NULL"
SAF_023: "Ciphertext shouldn't be BLANK OR NULL"
SAF_024: "Key Alias shouldn't be BLANK OR NULL"
SAF_025: "Associate Data shouldn't be BLANK OR NULL, Simply remove this call if you dont want to provide Associated Data"
SAF_026: "Associate Data shouldn't be BLANK OR NULL, Simply remove this parameter if you dont want to provide Associated Data"
SAF_027: "TAG shouldn't be BLANK OR NULL"
SAF_028: "Interoperable Language shouldn't be NULL"
SAF_029: "TAG is not required while using Interoperability Language [{0}] with default algorithm [{1}] for decryption"
SAF_030: "TAG is required while using Interoperability Language [{0}] with default algorithm AES_GCM for decryption"
SAF_031: "Password shouldn't be BLANK OR NULL"
SAF_032: "Plaintext File shouldn't be NULL"
SAF_033: "Ciphertext File shouldn't be NULL"